name: ggj_repair
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  english_words: ^3.1.5
  provider: ^3.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - lib/assets/backgrounds/background1.jpg
   - lib/assets/backgrounds/eye_open.jpg
   - lib/assets/backgrounds/eye_close.jpg
   - lib/assets/backgrounds/forest_scene1.jpg
   - lib/assets/backgrounds/forest_scene2.jpg
   - lib/assets/backgrounds/forest_scene3.jpg
   - lib/assets/backgrounds/map.jpg
   - lib/assets/backgrounds/surgery_bed.jpg
   - lib/assets/backgrounds/surgery_room.jpg
   - lib/assets/backgrounds/village_morning.jpg
   - lib/assets/backgrounds/village_night.jpg
   - lib/assets/Blink.png
   - lib/assets/Blinkw.png
   - lib/assets/icons/bag.png
   - lib/assets/icons/caution.png
   - lib/assets/icons/coin.png
   - lib/assets/icons/heart.png
   - lib/assets/icons/house.png
   - lib/assets/json/scenes/testing.json
   - lib/assets/characters/ex-gf-normal.png
   - lib/assets/characters/newbody-hanging.png
   - lib/assets/characters/newbody-operation.png
   - lib/assets/characters/random-girl-1-crying.png
   - lib/assets/characters/random-girl-1-normal.png
   - lib/assets/characters/random-girl-2-normal.png
   - lib/assets/characters/random-girl-3-normal.png
   - lib/assets/characters/random-girl-4-normal.png
   - lib/assets/characters/random-girl-5-normal.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
